project:
  type: website
  output-dir: docs

website:
  title: "Delilah Acosta"
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: Projects.qmd
      - text: Resume
        href: Resume.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Dacosta02
      - icon: linkedin
        href: https://www.linkedin.com/in/delilah-acosta-697a7429a/
format:
  html:
    theme:
      - morph
    css: styles.css
    toc: true

editor: visual

